version: "3.7"
services:
  quiz-server:
    build: .
    restart: unless-stopped
    environment:
      MEDIA_SERVER: "http://a.localhost:8080"
    volumes:
      - ./animedb.sqlite:/animedb.sqlite:ro
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./deployment/Caddyfile:/etc/caddy/Caddyfile
      - ./quiz/client/serve:/serve
      - ./openings:/openings
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
