version: "3.7"
services:
  game-server:
    build: .
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
      - ./game:/app/game
      - ./logs:/logs
    command: npx tsx watch ./game/index.ts
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./deployment/Caddyfile:/etc/caddy/Caddyfile
      - ./game/client/serve:/serve
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
