version: "3.7"
services:
  game-server:
    build: .
    restart: unless-stopped
    environment:
      MEDIA_SERVER: "http://media.localhost:8080"
    volumes:
      - ./logs:/logs
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./deployment/Caddyfile:/etc/caddy/Caddyfile
      - ./game/client/serve:/serve
      - ./media:/media
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
